2024-06-27 08:12:57,219 - distributed.nanny - INFO -         Start Nanny at: 'tcp://128.117.208.62:39211'
2024-06-27 08:13:00,933 - distributed.worker - INFO -       Start worker at: tcp://128.117.208.62:43549
2024-06-27 08:13:00,933 - distributed.worker - INFO -          Listening to: tcp://128.117.208.62:43549
2024-06-27 08:13:00,933 - distributed.worker - INFO -           Worker name:              PBSCluster-10
2024-06-27 08:13:00,933 - distributed.worker - INFO -          dashboard at:       128.117.208.62:44127
2024-06-27 08:13:00,933 - distributed.worker - INFO - Waiting to connect to: tcp://128.117.208.86:37311
2024-06-27 08:13:00,933 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:00,934 - distributed.worker - INFO -               Threads:                          1
2024-06-27 08:13:00,934 - distributed.worker - INFO -                Memory:                   3.73 GiB
2024-06-27 08:13:00,934 - distributed.worker - INFO -       Local Directory: /glade/derecho/scratch/mdfowler/tmp/dask-scratch-space/worker-tnuxl8ut
2024-06-27 08:13:00,934 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:18,576 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-06-27 08:13:18,578 - distributed.worker - INFO -         Registered to: tcp://128.117.208.86:37311
2024-06-27 08:13:18,578 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:18,579 - distributed.core - INFO - Starting established connection to tcp://128.117.208.86:37311
2024-06-27 09:09:45,014 - distributed.nanny.memory - WARNING - Worker tcp://128.117.208.62:43549 (pid=19904) exceeded 95% memory budget. Restarting...
2024-06-27 09:09:45,145 - distributed.nanny - INFO - Worker process 19904 was killed by signal 15
2024-06-27 09:09:45,153 - distributed.nanny - WARNING - Restarting worker
2024-06-27 09:09:49,510 - distributed.worker - INFO -       Start worker at: tcp://128.117.208.62:46245
2024-06-27 09:09:49,510 - distributed.worker - INFO -          Listening to: tcp://128.117.208.62:46245
2024-06-27 09:09:49,510 - distributed.worker - INFO -           Worker name:              PBSCluster-10
2024-06-27 09:09:49,510 - distributed.worker - INFO -          dashboard at:       128.117.208.62:32809
2024-06-27 09:09:49,510 - distributed.worker - INFO - Waiting to connect to: tcp://128.117.208.86:37311
2024-06-27 09:09:49,510 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 09:09:49,510 - distributed.worker - INFO -               Threads:                          1
2024-06-27 09:09:49,510 - distributed.worker - INFO -                Memory:                   3.73 GiB
2024-06-27 09:09:49,510 - distributed.worker - INFO -       Local Directory: /glade/derecho/scratch/mdfowler/tmp/dask-scratch-space/worker-lwj5ijn_
2024-06-27 09:09:49,510 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 09:09:55,372 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-06-27 09:09:55,375 - distributed.worker - INFO -         Registered to: tcp://128.117.208.86:37311
2024-06-27 09:09:55,375 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 09:09:55,376 - distributed.core - INFO - Starting established connection to tcp://128.117.208.86:37311
2024-06-27 10:54:32,796 - distributed.worker - ERROR - Worker stream died during communication: tcp://128.117.208.106:45739
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/core.py", line 342, in connect
    comm = await wait_for(
           ^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/utils.py", line 1935, in wait_for
    return await fut
           ^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/tcp.py", line 560, in connect
    convert_stream_closed_error(self, e)
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <distributed.comm.tcp.TCPConnector object at 0x14ddafe55450>: ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/worker.py", line 2857, in get_data_from_worker
    comm = await rpc.connect(worker)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1619, in connect
    return await self._connect(addr=addr, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1563, in _connect
    comm = await connect(
           ^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/core.py", line 368, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://128.117.208.106:45739 after 30 s
2024-06-27 10:55:32,268 - distributed.core - INFO - Connection to tcp://128.117.208.86:37311 has been closed.
2024-06-27 10:55:32,270 - distributed.worker - INFO - Stopping worker at tcp://128.117.208.62:46245. Reason: worker-handle-scheduler-connection-broken
2024-06-27 10:55:32,272 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://128.117.208.62:49570 remote=tcp://128.117.208.86:37311>
Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
             ^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/tcp.py", line 263, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2024-06-27 10:55:32,275 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://128.117.208.62:39211'. Reason: worker-handle-scheduler-connection-broken
2024-06-27 10:55:32,281 - distributed.nanny - INFO - Worker closed
2024-06-27 10:55:34,948 - distributed.nanny - INFO - Closing Nanny at 'tcp://128.117.208.62:39211'. Reason: nanny-close-gracefully
2024-06-27 10:55:34,949 - distributed.dask_worker - INFO - End worker
