2024-06-24 06:40:16,416 - distributed.nanny - INFO -         Start Nanny at: 'tcp://128.117.208.85:40421'
2024-06-24 06:40:18,158 - distributed.worker - INFO -       Start worker at: tcp://128.117.208.85:33033
2024-06-24 06:40:18,158 - distributed.worker - INFO -          Listening to: tcp://128.117.208.85:33033
2024-06-24 06:40:18,158 - distributed.worker - INFO -           Worker name:              PBSCluster-14
2024-06-24 06:40:18,158 - distributed.worker - INFO -          dashboard at:       128.117.208.85:43179
2024-06-24 06:40:18,158 - distributed.worker - INFO - Waiting to connect to: tcp://128.117.208.102:45151
2024-06-24 06:40:18,158 - distributed.worker - INFO - -------------------------------------------------
2024-06-24 06:40:18,158 - distributed.worker - INFO -               Threads:                          1
2024-06-24 06:40:18,158 - distributed.worker - INFO -                Memory:                   9.31 GiB
2024-06-24 06:40:18,158 - distributed.worker - INFO -       Local Directory: /glade/derecho/scratch/mdfowler/tmp/dask-scratch-space/worker-cz02x0on
2024-06-24 06:40:18,158 - distributed.worker - INFO - -------------------------------------------------
2024-06-24 06:40:21,241 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-06-24 06:40:21,243 - distributed.worker - INFO -         Registered to: tcp://128.117.208.102:45151
2024-06-24 06:40:21,244 - distributed.worker - INFO - -------------------------------------------------
2024-06-24 06:40:21,244 - distributed.core - INFO - Starting established connection to tcp://128.117.208.102:45151
ERROR 1: PROJ: proj_create_from_database: Open of /glade/u/apps/opt/conda/envs/npl-2024a/share/proj failed
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:10: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:33: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:33: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:33: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:33: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:33: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:33: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:33: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
/glade/derecho/scratch/mdfowler/tmp/ipykernel_68900/2848046507.py:33: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
2024-06-24 06:48:44,715 - distributed.core - INFO - Connection to tcp://128.117.208.102:45151 has been closed.
2024-06-24 06:48:44,766 - distributed.worker - INFO - Stopping worker at tcp://128.117.208.85:33033. Reason: worker-handle-scheduler-connection-broken
2024-06-24 06:48:44,768 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/worker.py", line 1252, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/utils_comm.py", line 455, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/utils_comm.py", line 434, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1391, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1619, in connect
    return await self._connect(addr=addr, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1563, in _connect
    comm = await connect(
           ^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/core.py", line 377, in connect
    handshake = await comm.read()
                ^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/tcp.py", line 237, in read
    convert_stream_closed_error(self, e)
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://128.117.208.85:35464 remote=tcp://128.117.208.102:45151>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-06-24 06:48:44,773 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://128.117.208.85:40421'. Reason: worker-handle-scheduler-connection-broken
2024-06-24 06:48:44,869 - distributed.client - ERROR - Failed to reconnect to scheduler after 30.00 seconds, closing client
2024-06-24 06:48:44,879 - distributed.nanny - INFO - Worker closed
2024-06-24 06:48:49,649 - distributed.nanny - INFO - Closing Nanny at 'tcp://128.117.208.85:40421'. Reason: nanny-close-gracefully
2024-06-24 06:48:49,650 - distributed.dask_worker - INFO - End worker
