2024-06-27 08:12:57,220 - distributed.nanny - INFO -         Start Nanny at: 'tcp://128.117.208.62:41175'
2024-06-27 08:13:00,933 - distributed.worker - INFO -       Start worker at: tcp://128.117.208.62:38625
2024-06-27 08:13:00,933 - distributed.worker - INFO -          Listening to: tcp://128.117.208.62:38625
2024-06-27 08:13:00,933 - distributed.worker - INFO -           Worker name:              PBSCluster-21
2024-06-27 08:13:00,933 - distributed.worker - INFO -          dashboard at:       128.117.208.62:33647
2024-06-27 08:13:00,933 - distributed.worker - INFO - Waiting to connect to: tcp://128.117.208.86:37311
2024-06-27 08:13:00,934 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:00,934 - distributed.worker - INFO -               Threads:                          1
2024-06-27 08:13:00,934 - distributed.worker - INFO -                Memory:                   3.73 GiB
2024-06-27 08:13:00,934 - distributed.worker - INFO -       Local Directory: /glade/derecho/scratch/mdfowler/tmp/dask-scratch-space/worker-o6k63bqc
2024-06-27 08:13:00,934 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:18,572 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-06-27 08:13:18,573 - distributed.worker - INFO -         Registered to: tcp://128.117.208.86:37311
2024-06-27 08:13:18,573 - distributed.worker - INFO - -------------------------------------------------
2024-06-27 08:13:18,574 - distributed.core - INFO - Starting established connection to tcp://128.117.208.86:37311
2024-06-27 10:54:39,210 - distributed.worker - ERROR - Worker stream died during communication: tcp://128.117.208.106:45739
Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/utils.py", line 1935, in wait_for
    return await fut
           ^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/tcp.py", line 547, in connect
    stream = await self.client.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/tornado/tcpclient.py", line 279, in connect
    af, addr, stream = await connector.start(connect_timeout=timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/core.py", line 342, in connect
    comm = await wait_for(
           ^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/utils.py", line 1934, in wait_for
    async with asyncio.timeout(timeout):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/worker.py", line 2056, in gather_dep
    response = await get_data_from_worker(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/worker.py", line 2857, in get_data_from_worker
    comm = await rpc.connect(worker)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1619, in connect
    return await self._connect(addr=addr, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/core.py", line 1563, in _connect
    comm = await connect(
           ^^^^^^^^^^^^^^
  File "/glade/u/apps/opt/conda/envs/npl-2024a/lib/python3.11/site-packages/distributed/comm/core.py", line 368, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://128.117.208.106:45739 after 30 s
2024-06-27 11:01:34,268 - distributed.core - INFO - Connection to tcp://128.117.208.86:37311 has been closed.
2024-06-27 11:01:34,269 - distributed.worker - INFO - Stopping worker at tcp://128.117.208.62:38625. Reason: worker-handle-scheduler-connection-broken
2024-06-27 11:01:34,283 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://128.117.208.62:41175'. Reason: worker-handle-scheduler-connection-broken
2024-06-27 11:01:34,291 - distributed.nanny - INFO - Worker closed
2024-06-27 11:01:38,039 - distributed.nanny - INFO - Closing Nanny at 'tcp://128.117.208.62:41175'. Reason: nanny-close-gracefully
2024-06-27 11:01:38,042 - distributed.dask_worker - INFO - End worker
